### ISSUE TITLE
Ignore exceptions

### ISSUE THREAD

**Issue by breml** [frapposelli/wwhrd#16]
I would like to use `wwhrd` in our CI pipeline and I would like to have it silent (with `-q`), that is without any output, if there are no license violations to take care of. This is, if an exception is granted by adding it to `.wwhrd.yml` and the flag `-q` is given, I would like to have no output.

Would you accept a PR to add this functionality? Should this be implemented as an additional flag to maintain the backwards compatibility?

**Comment by frapposelli** [comment]
I think we should probably just raise the default log level to `Error` for the `-q` flag, this would make a run with exceptions silent.
