### ISSUE TITLE
Flag to disable colored output

### ISSUE THREAD

**Issue by breml** [frapposelli/wwhrd#17]
To post process the output provided by `wwhrd` it would be nice to have a flag to disable the colored output. The used library for the output does support an option called [`DisableColors`](https://godoc.org/github.com/sirupsen/logrus#TextFormatter), which to my knowledge could be used to achieve this in a simple way.

Would you accept a PR for this?

**Comment by frapposelli** [comment]
@breml by default colors should be omitted if the command is not run from a TTY, but I would gladly accept a PR for an explicit flag!
