### ISSUE TITLE
vgo support

### ISSUE THREAD

**Issue by alikor** [frapposelli/wwhrd#22]
Hello 

Are you planning on supporting vgo anytime soon?

Madu

**Comment by frapposelli** [comment]
that's a very good question 😄

I haven't looked at `vgo` yet, but it's definitely on my radar, I'll update this issue once get to it.

**Comment by tzneal** [comment]
In go modules world, at least for now you can do a :

```
go mod vendor
wwhrd
rm -rf vendor
```
