### ISSUE TITLE
Update go-license dependency

### ISSUE THREAD

**Issue by breml** [frapposelli/wwhrd#25]
The current version of `wwhrd` does not recognize the license file in [godotenv](https://github.com/joho/godotenv), because the license file is called `LICENCE` (British-English), see https://github.com/joho/godotenv/issues/78.

After digging into the issue I found out, that `wwhrd` uses a out dated version of [go-license](https://github.com/ryanuber/go-license). The latest version of this library also accepts the British version of the license file name (see: https://github.com/ryanuber/go-license/blob/master/license.go#L40).

It would be nice, if `wwhrd` could be updated to use the newest version of `go-license`.

I offer to provide a PR for this, but I was not able to find out, what you are using to manage the `vendor/` folder. Maybe this is the time to switch to Go modules and solve #22  at the same time. I can help with that as well.

**Comment by frapposelli** [comment]
Very good point, I'll make the necessary changes to fix this.

**Comment by frapposelli** [comment]
Version `v0.2.2` is now available 😄

**Comment by breml** [comment]
@frapposelli Thank you very much for your fast fix, I will give it a try tomorrow.
