### ISSUE TITLE
Update or remove vendor folder

### ISSUE THREAD

**Issue by breml** [frapposelli/wwhrd#27]
When I run `GO111MODULE=on go mod vendor` a lot of packages get updated in the `vendor` folder so I suggest to either commit an updated version of the `vendor` folder or remove it completely.

**Comment by frapposelli** [comment]
thanks for the heads up!, looks like I forgot to re-vendor the dependencies I changed yesterday and the binaries for 0.2.3 got built with the old vendor folder, not picking up the new packages.

I've just cut 0.2.4 and should be available as soon as CI finishes.

**Comment by breml** [comment]
@frapposelli thanks for your swift feedback and the new release.
