### ISSUE TITLE
Release on GoReleaser

### ISSUE THREAD

**Issue by mastertinner** [frapposelli/wwhrd#29]
It would be very convenient if this project could be installed via [GoReleaser](https://goreleaser.com/). Installing it via `go get -u` is not optimal because that doesn't install the latest released version but rather the latest state of the `master` branch.

**Comment by frapposelli** [comment]
Hi @mastertinner the project is indeed available as a binary release (released through goreleaser nonetheless 😄 ), see the README.md for homebrew install steps or check out the [releases](https://github.com/frapposelli/wwhrd/releases) page for docker containers and binaries alike.

**Comment by mastertinner** [comment]
Thanks for your quick reply and sorry for missing that!
