### ISSUE TITLE
Wrongly detected license for github.com/opencontainers/go-digest

### ISSUE THREAD

**Issue by breml** [frapposelli/wwhrd#51]
I discovered an other case, where the license is wrongly detected: [github.com/opencontainers/go-digest](https://github.com/opencontainers/go-digest)

`wwhrd` does detect this package as `CC-BY-SA-4.0`, but this is the license for the documentation (https://github.com/opencontainers/go-digest/blob/master/LICENSE.docs). The license for the software is `Apache-2.0` (https://github.com/opencontainers/go-digest/blob/master/LICENSE).

**Comment by frapposelli** [comment]
Thanks, added to the backlog, I'll take a look next Tuesday
